# Minimal configuration based on Antora Generator Template 
# Source: https://code.asam.net/common/templates/antora-base-repo-example/-/blob/standard_generator/site.yml
# tag::site[]
site:
  title: ASAM OpenCRG®
  url: https://asam-ev.github.io/OpenCRG/
  start_page: asamopencrg:specification:index.adoc
# end::site[]
urls: # Creates a redirect for the newest version to the link "latest"
  latest_version_segment_strategy: redirect:to
  latest_version_segment: latest

# tag::content[]
content:
  sources:
  - url: https://code.asam.net/common/asam-terminology.git
    start_path: .antora
    tags: [v*,V*]
  - url: .
    start_path: .antora
    tags: ['v*', '!v2.0.0', '!v1.2.1', '!v_1_1_2'] # Exclude old versions that are not build with antora
    branches: ['master']
# end::content[]

ui:
  bundle:
    url: https://code.asam.net/common/antora-ui/-/jobs/artifacts/main/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental_ui # Activate this if you need to make local UI changes. Check the official Antora documentation for more information.

output:
  clean: true
  dir: ./site
runtime:
  fetch: true

# tag::attributes[]
asciidoc:
  attributes:
    page-pagination: true
    hide-uri-scheme: ""
    kroki-server-url: 'http://kroki:8000'
    kroki-fetch-diagram: ""
    # Allow URI read to retrieve SVG on compilation
    allow-uri-read: true
    # use SVG unless otherwise specified
    kroki-default-format: svg
    # Make SVG inline so that we can get interactive (can be overridden by schema with "opts=none")
    kroki-default-options: interactive
    sectnums: "@"
    xrefstyle: short@
    listing-caption: Code
    page-width-limit: none@
    THIS_STANDARD: ASAM OpenCRG


# end::attributes[]

  extensions:
  - asciidoctor-kroki
  - './doc/antora_sources/asam-antora-extensions/asam-asciidoctor_extensions.js'
  - './doc/antora_sources/asam-antora-extensions/asam-asciidoctor_extensions-registered.js'

antora:
  extensions:
    - require: '@antora/lunr-extension'
    - require: './doc/antora_sources/asam-antora-extensions/asam-antora_extension.js'
      orphan_exceptions: '/'
      numbered_titles: true
      section_number_style: 'iso'
      alternate_xref_style: 'full'
      loft: true
      local_to_global_references: false
      bibliography: true
