== General Architecture
:imagesdir: ../OpenDRIVE_1_6/images/3_General_architecture/
:stem: latexmath

=== File Structure

OpenDRIVE data is stored in XML files with the extension .xodr. Compressed OpenDRIVE files have the extension ".xodrz" (compression format: gzip).

The OpenDRIVE file structure conforms to XML rules; the associated schema file is referenced in the XML. The schema file for the OpenDRIVE® format can be retrieved from https://www.asam.net/standards/detail/opendrive/

Elements are organized in levels. Elements with a level that is greater than zero (0) are children of the preceding level. Elements with a level of one (1) are called primary elements.

Each element can be extended with user-defined data. This data is stored in so-called user data elements.

All floating-point numbers used in OpenDRIVE are IEEE 754 double precision floating-point numbers. In order to ensure accurate representation of floating-point numbers in the XML representation, implementations SHOULD use a known correct accuracy preserving minimal floating-point printing algorithm (e.g. [Burger96], [Adams18]), or ensure that 17 significand decimal digits are always produced (e.g. using the "%.17g" ISO C printf modifier). Importing implementations should use a known correct accuracy preserving floating-point reading algorithm (e.g. [Clinger90]).

[Burger96] Robert G. Burger and R. Kent Dybvig: "Printing floating-point numbers quickly and accurately." In proceedings of ACM SIGPLAN 1996 conference on Programming Language Design and Implementation, Philadelphia, PA, USA, May 1996, pp. 108-116

[Adams18] Ulf Adams: "Ryū: fast float-to-string conversion." ACM SIGPLAN Notices, Vol. 53, No. 4, April 2018, pp. 270-282

[Clinger90] William D. Clinger: "How to Read Floating Point Numbers Accurately." ACM SIGPLAN Notices, Vol. 25, No. 6, June 1990, pp. 92-101

=== Combining Files

Multiple files can be combined with an <include> tag at the appropriate locations. Upon parsing this tag, OpenDRIVE readers shall immediately start reading the file specified as attribute of the tag. It is the user’s responsibility to make sure that contents read from an include file are consistent with the context from which the inclusion starts.

The parent tag under which the <include> tag occurs must be present in both, the parent file and the included file.

Example:

*Original File*

[source, xml]
----
<planView>
  <include file="planview.xml"/>
</planView>
----

*Included File*

[source, xml]
----
<planView>
  <geometry x="-0.014" y="-0.055" hdg="2.88" length="95.89" s="0.0">
    <arc curvature="-0.000490572"/>
  </geometry>
  <geometry x="-92.10" y="26.64" hdg="2.84" length="46.65" s="95.89">
    <spiral curvStart="-0.000490572" curvEnd="-0.004661241"/>
  </geometry>
</planView>
----

=== Attributes used in the file

All attributes that can be used in an OpenDRIVE file are fully annotated in the UML model: 

*	If *units* are applicable to an attribute, these are stated according to 1.4.2 Units.
*	*Type*: Describes the data type of an attribute. It can be either a primitive data type, for example, string, double, float, or a complex data type that refers to an object described within this specification.
•	*Value*: Value determines the value range of the given attribute relative to the specified type

==== Enclosing element

The overall enclosing element of the file is:
.Attributes of the OpenDRIVE element
[cols="30,70"]
|===
|*delimiters*	|`<OpenDRIVE>...</OpenDRIVE>`
|*parent*	    |none
|*instances*	|1
|*attributes*	|`xmlns`="http://www.opendrive.org"
|===

==== Header

The `<header>` element is the very first element within the <OpenDRIVE> element.

.Attributes of the header element
[cols="15,15,15,15,40"]
|===
2+|*delimiters*	3+|`<header>...</header>`
2+|*parent*       3+|`<OpenDRIVE>`
2+|*instances*	3+|1
2+|*attributes*	3+| 
|*name*     |*type*     |*unit*     |*value*    |*description*
|`revMajor`	|ushort     |-	        |1	        |Major revision number of OpenDRIVE format 
|`revMinor`	|ushort	    |-	        |6          |Minor revision number of OpenDRIVE format; 6 for OpenDrive 1.6 
|`name`	    |string	    |-	        |-	        |Database name
|`version`	|string 	|-	        |-          |Version of this road network
|`date`	    |string	    |-	        |-	        |Time/date of database creation according to ISO 8601 (preference: YYYY-MM-DDThh:mm:ss)
|`north`	|double	    |m	        |-	        |Maximum inertial y value
|`south`	|double	    |m	        |-	        |Minimum inertial y value
|`east`	    |double	    |m	        |-	        |Maximum inertial x value
|`west`	    |double	    |m	        |-	        |Minimum inertial x value
|`vendor`	|string	    |-	        |-	        |Vendor name
|===

=== General rules and assumptions

==== Traffic direction

Unless stated otherwise, all examples, figures, and descriptions in this specification assume right-hand traffic.