==== Options

The optional _options_ section defines values for options. Options influence the evaluation of OpenCRG data. They do not modify the road data itself.

//TODO think again, how to make this paragraph more understandable.
A creator of an OpenCRG file must not rely on applications evaluating the data with options set to the values specified in the OpenCRG file. Applications shall define default values for options. Applications may use options provided in an OpenCRG file to override these default values. A creator of an OpenCRG file may thus use the _options_ section to express the intended option settings.

An OpenCRG file may specify options without having a section containing road data. Such a file may be referenced in another OpenCRG file, which contains the road data, and be used as a control file.

Border mode options and border offset options influence the returned z-values when the u/v-coordinates in a query exceed the defined road in the respective direction. These options may be used to mark borders, provide fallback values, or to extend the data beyond the defined area.

Border-smoothing options provide a linear ascend or descend of z-values along a defined range at the beginning and the end of the road. These options can be used to smooth abrupt changes in road data at the beginning or the end of the road, for example, in order to reduce unwanted high-frequency input in vibration simulation.

When the u-coordinate exceeds the defined range, the corresponding x/y-coordinates are calculated by either extrapolating the reference line or evaluating the reference line as closed track. The reference-line-continuation option defines whether the reference line is extrapolated or treated as closed track. A track can be closed, if the extrapolated tracks intersect at an angle of less than 60 degree.

===== Keyword

----
$ROAD_CRG_OPTS
----

===== Contents

The _options_ section contains options provided as key-value pairs.

.Option parameters
|===
|Option |Values |Description

|`BORDER_MODE_U`
|0, 1, 2, 3, 4 (default: 2)
a|Returned z-value, when a query exceeds the beginning or the end of the road.

0:: Return NaN or an error.
1:: Return 0.
2:: Return the last valid z-value at the given v-coordinate.
3:: Repeat road data before the beginning and after the end of the road.
4:: Mirror road data at the beginning and the end of the road.

|`BORDER_MODE_V`
|0, 1, 2, 3, 4 (default: 2)
a|Returned z-value, when a query exceeds the left side or the right side of the road.

0:: Return NaN or an error.
1:: Return 0.
2:: Return the last valid z-value at the given u-coordinate.
3:: Repeat road data after the left side and the right side of the road.
4:: Mirror road data at the left side and the right side of the road.

|`BORDER_OFFSET_U`
|Double-precision floating-point number (default: 0.0)
|Offset for returned z-value, when a query exceeds the beginning or the end of the road.

|`BORDER_OFFSET_V`
|Double-precision floating-point number (default: 0.0)
|Offset for returned z-value, when a query exceeds the left side or the right side of the road.

|`BORDER_SMOOTH_UBEG`
|Double-precision floating-point number from 0.0 to u~max~ (default: 0.0)
|Range for scaling z-values linearly from 0 to the actual value, including slope and banking. Provides a smooth increase of road data at the beginning of the road.

|`BORDER_SMOOTH_UEND`
|Double-precision floating-point number from 0.0 to u~max~ (default: 0.0)
|Range for scaling z-values linearly from the actual value to 0. Provides a smooth decrease of road data at the end of the road.

|`REFLINE_CONTINUATION`
|0, 1 (default: 0)
a| Mode for computing x/y-positions if a given u-coordinate is positioned outside the defined reference line.

0:: Extrapolate the reference line at both ends.
1:: Treat reference line as closed track, if possible.

|`WARN_MSGS`
|-1, 0, [1;∞[ (default: -1)
a|Number of warning messages displayed.

-1:: All.
0:: None.
[1;∞[:: Max. number.

|`WARN_CURV_LOCAL`
|0, 1 (default: 0)
a|Check whether local curvature limit is exceeded.

0:: Do not check local curvature.
1:: Check local curvature.

|`WARN_CURV_GLOBAL`
|0, 1 (default: 0)
a|Check whether global curvature limit is exceeded.

0:: Do not check global curvature.
1:: Check global curvature.

|`CHECK_EPS`
| [1e-6; 1e-2] (default: 1e-6)
a|Expected minimal accuracy, used for numerical consistency checks.

|`CHECK_INC`
|less than 0.001*(1-CHECK_EPS) or abs(round(CHECK_INC=0.001 * (1-CHECK_EPS)) 0.001 * (1-CHECK_EPS) * CHECK_INC) > CHECK_EPS * max(0.001 * (1-CHECK_EPS); CHECK_INC) (default: 1e-3)
a|Expected minimum increment, used for numerical consistency checks.

|`CHECK_TOL`
|[CHECK_EPS*CHECK_INC; 0.5*CHECK_INC] (default: 0.1*CHECK_INC)
a|Expected absolute tolerance, used for numerical consistency checks.

|`CHECK_PRO`
|[0.1*CHECK_INC; 1] (default: 5e-3)
a|Expected projection tolerance, used for numerical consistency checks.

|`CHECK_WGS`
|[0.1*CHECK_INC; 1000] (default: 10)
a|Expected WGS 84 tolerance, used for numerical consistency checks.
|===

===== Rules

* An OpenCRG file may contain an _options_ section.
* Options in an _options_ section shall be provided as key-value pairs using the syntax `OPTION = value`.
* An _options_ section may be empty.
* If the data in an OpenCRG file is intended to be evaluated with options set to specific values, these values should be specified in the OpenCRG file.
* Applications shall define default values for options. Options defined in an OpenCRG file may override these default values.

===== Examples

The following example illustrates how to create an endless road using a border mode option. The border smoothing prevents unnecessary steep changes at the beginning and the end of the road.

----
$ROAD_CRG_OPTS
BORDER_MODE_U       = 3   ! return 0 when query exceeds the beginning or
                          !  end of the road
BORDER_SMOOTH_UBEG  = 0.5 ! over the first 2 m, increase z-values linearly
                          ! from 0 to the actual value
BORDER_SMOOTH_UEND  = 0.5 ! over the last 2 m, decrease z-values linearly
                          ! from 0 to the actual value
$!*********************
----



