==== Road data
:imagesdir: images/
:stem: latexmath

The _road data_ section contains the actual road surface data. Road surface data is not limited to road elevation, although this is the primary use case. For example, an OpenCRG file may contain friction coefficients or color values.

Road data is stored as low-precision array as defined in the _data definition_ section. Columns are longitudinal cuts parallel to the reference line. Rows are lateral cuts orthogonal to the reference line. Additional columns may contain reference line data, such as heading angle, banking or slope.

A single record shall contain a maximum of 80 byte. If the defined data channels exceed this limit, the respective data row shall be wrapped to the next record. In plain-text format, each data row shall start in a new record. In binary format, records are successively filled up to 80 byte. The last record is padded with NaNs.

In plain-text formats, numbers are represented as follows:

* Numbers of type real are 10 characters long for a maximum of 8 numbers per record.
* Numbers of type double are 20 characters long for a maximum of 4 numbers per record.
* Numbers shall be represented using fixpoint or scientific format.
* NaNs are represented by a placeholder with a leading asterisk (`*`).

In binary formats, numbers are represented as follows:

* Numbers shall be represented using IEEE Big Endian format.
* Numbers of type real are 4 byte long for a maximum of 20 numbers per record.
* Numbers of type double are 8 byte long for a maximum of 10 numbers per record.
* NaNs are represented according to IEEE 754.

===== Keyword

none

===== Rules

* An OpenCRG file may contain a _road data_ section.
* The _road data_ section shall be the last section of an OpenCRG file.
* Data formatting shall match the definitions in the _data definition_ section.
* The _road data_ section may contain other data than elevation.

===== Examples

The example shows road data for a 1 m wide road. The road data is organized in a 4-by-10 matrix. The first column contains heading angles of the reference line. The following three columns contain actual road surface data. One value on the right border of the road is missing.

.Plain-text road data with 4 columns and 10 rows
----
$ROAD_CRG                          ! road parameters section
REFERENCE_LINE_INCREMENT =  0.50   ! 10 cm between every lateral cut
LONG_SECTION_V_RIGHT     = -0.50   ! right road border
LONG_SECTION_V_RIGHT     =  0.50   ! left road border
LONG_SECTION_V_INCREMENT =  0.50   ! 50 cm between every longitudinal cut
$!********************************
$KD_DEFINiTION                     ! data definition section
#:LRBI                             ! plain-text data, numbers of type real
D:reference line phi,rad           ! heading angle
D:long section 1,m                 ! 0.50m right of reference line
D:long section 2,m                 !             on reference line
D:long section 3,m                 ! 0.50m  left of reference line
$!********************************
$
0.0000000 0.0000000 0.0000000 0.0000000
0.0000000 0.0000000 0.0000000 0.0000000
0.0000000 0.0000000 0.0000000 0.0000000
0.0000000 0.0111111 0.0111111 0.0000000
0.0000000 0.0000000 0.0000000 0.0000000
0.0111111 *missing* 0.0000000 0.0111111
0.0111111 0.0111111 0.0111111 0.0222222
0.0111111 0.0111111 0.0222222 0.0333333
0.0111111 0.0111111 0.0111111 0.0222222
0.0111111 0.0000000 0.0000000 0.0111111
----
