=== Conventions
:imagesdir: ../images/
:stem: latexmath

==== Naming conventions 
In this document, the following conventions apply:

``data types`` 	are given according to IEEE standards.

==== Units

Unless stated otherwise, all numeric values within this specification are in SI units, for example:

*	position/distance	in [m]
*	angles	in [rad]

Geographic positions are stated in the unit defined by the spatial coordinate system, for example, in accordance with WGS 84 – EPSG 4326.

==== Modal verbs

To ensure compliance with the OpenCRG standard, users must be able to distinguish between mandatory requirements, recommendations, permissions, as well as possibilities, capabilities, obligations and necessities.

The following rules for using modal verbs apply:

.Rules for using modal verbs
[%header, cols=2*]
|===
|Provision									|Verbal form
|*Requirement* +
Requirements shall be followed strictly in order to be conform to the standard. Deviations are not allowed.	
|shall +
shall not

|*Recommendation* +
Recommendations indicate that among several possibilities, one is recommended as particularly suitable, without mentioning or excluding others.	
|should +
should not

|*Permission* +
Permissions indicate a course of action permissible within the limits of OpenCRG deliverables.	
|may + 
need not

|*Possibility and capability* +
These verbal forms are used for stating possibilities or capabilities, being technical, material, physical, or others.	
|can +
can not

|*Obligation and necessity* +
These verbal forms are used to describe legal, organizational, or technical obligations and necessities that are not regulated or enforced by the OpenCRG standard.	
|must +
must not
|===

==== Typographic conventions

This documentation uses the following typographical conventions:

.Typographical conventions

//TODO check whether code snippets are actually blue

[%header, cols=2*]
|===
|Mark-up					|Definition
|`Code elements`			|This format is used for code elements, such as technical names of classes and attributes, as well as attribute values.
|```[blue]#Code snippets#``` 				|This format is used for excerpts of code that serve as an example for implementation.
|_Terms_						|This format is used to introduce glossary terms, new terms and to emphasize terms.
|`[green]#Mathematical elements#`	|This format is used for calculations and mathematical elements.
|===

==== Curvature

For curvature indications, the following convention applies: 

*	Positive curvature: left curve (counter-clockwise motion) 
*	Negative curvature: right curve (clockwise motion) 

`[green]#Curvature == 1/radius#`