=== Creating and deleting contact points

In order to evaluate data with the C-API, the user must create one or more _contact points_. Contact points provide access to a given data set. A contact point is identified by a unique integer ID. This ID is returned by the contact-point creation method. The number of contact points per data set is not limited.

[NOTE]
====
When creating multi-thread applications to parallelize evaluation calls, create a separate contact point for each thread. Sharing contact points across different threads will destroy data associated with that  contact point.
====

==== Prerequisites

- You have loaded an OpenCRG data set.
- You have set and applied modifiers.

==== Corresponding C functions

`int cpId = crgContactPointCreate( int dataSetId )`::
Create a contact point with the ID `cpId` for the data set `dataSetId`.

`int crgContactPointDelete( int cpId )`::
Delete the contact point with the ID `cpId`.

`int crgContactPointDeleteAll( int dataSetId )`::
Delete all contact points associated with the data set `dataSetId`.

==== Corresponding Matlab functions

The Matlab tools do not use contact points.

==== Examples

//REVIEW: maybe add this to the upper description
The contact point is relevant for the use of OpenCRG within the simulation. The contact point for example can be the touching point of the tire with the modelled road.

===== C examples

----
double z;

/* load CRG file */
int dataSetId = crgLoaderReadFile( 'demo.crg' );

/* create two contact points */
int cpId1 = crgContactPointCreate( dataSetId );
int cpId2 = crgContactPointCreate( dataSetId );
----

==== Related Topics

