=== Setting options

With the C-API, you set options via function calls. For all options and values, symbolic constants are defined in `_opencrg_/c-api/baselib/inc/crgBaseLib.h`. You should use the symbolic constants rather than their integer equivalents to make your code easier to read.


When you use the MATLAB tools to evaluate data, options stored with OpenCRG data are automatically taken into account. With MATLAB, you set options by directly accessing the `opts` field of a data set using dot notation.

[NOTE]
====
Options, whether defined in an OpenCRG file or via function calls, are applied automatically when executing an evaluation call.
====

==== Prerequisites

- You have loaded an OpenCRG data set.
- You have set and applied modifiers.
- You have created a contact point (C only).

==== Corresponding C functions

`int crgContactPointOptionSetInt( int cpId, unsigned int optionId, int optionValue )`::
Set the integer option `optionId` of the contact point `cpId` to the value `optionValue`.

`int crgContactPointOptionSetDouble( int cpId, unsigned int optionId, double optionValue )`::
Set the double option `optionId` of the contact point `cpId` to the value `optionValue`.

`int crgContactPointOptionGetInt( int cpId, unsigned int optionId, int* optionValue )`::
Get the current value of the integer option `optionId` of the contact point `cpId` and store it in `option value`.

`int crgContactPointOptionGetDouble( int cpId, unsigned int optionId, double* optionValue )`::
Get the current value of the double option `optionId` of the contact point `cpId` and store it in `option value`.

`void crgContactPointOptionsPrint( int cpId )`::
Print the current option settings of the contact point `cpId`.

`int crgContactPointOptionRemove( int cpId, unsigned int optionId )`::
Remove the option `optionID` from the contact point `cpId`.

`int crgContactPointOptionRemoveAll( int cpId )`::
Remove all options from the contact point `cpId`.

`void crgContactPointSetDefaultOptions( int cpId )`::
Set all options of the contact point `cpId` to their default values.

==== Corresponding MATLAB functions

Options are set by directly accessing the `opts` field of a data set using dot notation.

==== Examples

===== C examples

The following example shows how to set options using the C-API.

----
/* load CRG file */
int dataSetId = crgLoaderReadFile( 'demo.crg' );

/* create contact point */
int cpId = crgContactPointCreate( dataSetId );

/* set border mode options to "Return NaN" */
crgContactPointOptionSetInt( cpId, dCrgCpOptionBorderModeU, dCrgBorderModeNone );
crgContactPointOptionSetInt( cpId, dCrgCpOptionBorderModeV, dCrgBorderModeNone );

/* evaluate z at (u,v) = [100 0] */
crgEvaluv2z( cpId, 100, 0, &z );
----

===== MATLAB examples

The following example shows how to set options using the MATLAB tools.

----
% load CRG file 
data = crg_read('demo.crg');

% set border mode options to "Return NaN"
data.opts.bdmu = 0;
data.opts.bdmv = 0;

% plot road surface in u/v-coordinates
crg_show_road_uv2surface(data, u, v);
----

==== Related topics

* <<Options>>