=== Manipulating OpenCRG data

OpenCRG data is usually changed by applying modifiers or setting options. However, there are some changes that you cannot achieve with modifiers or options. An example is when you need to prepare real-world data for use in simulations.

The MATLAB tools cover the following use cases:

* Appending or cutting OpenCRG data sets.
* Extracting and changing slope and banking.
* Filtering and limiting z-values.
* Flipping road data or mapping it to different coordinate systems.

==== Prerequisites

* You have loaded an OpenCRG data set.

==== Corresponding C functions

The C-API does not provide functions for manipulating OpenCRG data.

==== Corresponding MATLAB functions

`[data, roff2] = crg_append(data1, data2)`::
Append an OpenCRG data set `data2` to the OpenCRG data set `data1` and return the resulting data set `data`. For a smooth connection, the second grid is re-positioned so that both grids overlap for one longitudinal increment. The re-positioned data set is returned as `roff2`. The last latitudinal cut of `data` and the first latitudinal cut of `data2` are dropped. Incomplete or inconsistent WGS 84 values at the intersection result in omitting the WGS 84 information in the result.

`[data] = crg_cut_iuiv(data, iu, iv)`::
Cut out a part of a OpenCRG road `data`. `iu` and `iv` specify the index positions of the area to be cut out.

`[data] = crg_separate_sb(data, swlen, bwlen)`::
Find and filter slope and banking in road data of `data`. Slope and banking are filtered using a moving average with window lenght `swlen` and `bwlen`, respectively. Separate the filtered result from the road data leaving the total elevation information unchanged. 

`[data] = crg_b2z(data, b)`::
Apply new banking `b` to the OpenCRG data in `data`. Merge existing banking into the road data.

`[data] = crg_s2z(data, rz)`::
Apply new slope defined by `rz` to the OpenCRG data in `data`. Merge existing slope into the road data.

`[data] = crg_ext_slope(data, p)`::
Extract the slope from OpenCRG data in `data`. `pp` is a smoothing parameter.

`[data] = crg_ext_banking(data, pp)`::
Extract the banking from OpenCRG data in `data`. `pp` is a smoothing parameter.

`[data] = crg_filter(data, iu, iv, fm, mask, wopt)`::
Filter OpenCRG data in `data`. `iu` and `iv` can be used to limit filtering to an area of the grid. `fm` specifies the filtering method. `mask` specifies the size of the filter mask. The optional `wopt` defines filter weights and number of repeated filter applications.

`[data] = crg_limiter(data, mmlim, iu, iv)`::
Limit z-values in `data` to the minimum and maximum defined in `mmlim`. `iu` and `iv` can be used to limit the operation to an area of the grid.

`[data] = crg_wrap(data)`::
Wrap heading angles of road parameters and road data in `data` to a +/- pi range.

`[data] = crg_flip(data)`::
Flip the OpenCRG data in `data`, swapping start and end while leaving the modifiers and options unchanged.

`[data] = crg_map_uv2uv(data, crg_uv, iu, iv)`::
Map z-values of `crg_uv` in u/v-coordinates to the u/v-grid of `data`. `iu` and `iv` can be used to limit the operation to an area of the grid.

`[data] = crg_map_xy2xy(data, crg_xy, iu, iv)`::
Map z-values of `crg_xy` in x/y-coordinates to the inertial x/y-coordinate system of `data`. `iu` and `iv` can be used to limit the operation to an area of the grid.

`[data] = crg_rerender(crg, inc, v)`::
Re-render OpenCRG data in `crg` as `data` with new u/v-increment `inc` and v-spacing `v`.

==== Examples

===== MATLAB examples

The following example shows how to manipulate data using the MATLAB tools.

----
% load OpenCRG data
data = crg_read('demo.crg');

% extract banking with smoothing
exdata = crg_ext_banking(data, 0.0000000000003);

% extract slope
exdata = crg_ext_slope(exdata);

% visualize results
crg_show_refline_elevation(exdata);
crg_show_elgrid_surface(exdata)
crg_show_road_surface(exdata);
----

==== Related topics

* <<Reading an OpenCRG file>>

