=== Manipulating OpenCRG data

OpenCRG data is usually changed by applying modifiers or setting options. However, some changes cannot be achieved with modifiers or options. This is common for changes to the actual data, for example, when preparing real-world data for use in simulations.

The Matlab tools cover the following use cases:

* Appending or cutting OpenCRG data sets.
* Extracting and changing slope and banking.
* Filtering and limiting z-values.
* Flipping road data or mapping it to different coordinate systems.

==== Prerequisites

* You have loaded an OpenCRG data set.

==== Corresponding C functions

The C-API does not provide functions for manipulating OpenCRG data.

//TODO: is this true? I did not find any.

==== Corresponding Matlab functions

`[data, roff2] = crg_append(data1, data2)`::
Append an OpenCRG data set `data2` to the OpenCRG data set `data1` and returns the resulting data set `data`. For a smooth connection, the second grid is re-positioned so that both grids overlap for one longitudinal increment. The re-positioned data set is returned as `roff2`. The last latitudinal cut of `data` and the first latitudinal cut of `data2` are dropped. Incomplete or inconsistent WGS84 values at the intersection will result in omitting the WGS84 information in the result.

`[data] = crg_cut_iuiv(data, iu, iv)`::
Cut out a part of a OpenCRG road `data`. `iu` and `iv` specify the index positions of the area to be cut out.

`[data] = crg_separate_sb(data, swlen, bwlen)`::
Find and filter slope and banking in road data of `data`. Slope and banking are filtered using a moving average with window lenght `swlen` and `bwlen` respectively. Separate the filtered result from the road data leaving the total elevation information unchanged. 

`[data] = crg_b2z(data, b)`::
Apply new banking `b` to the OpenCRG data in `data`. Merge existing banking into the road data.
//TODO: Please check whether this is true. Got this from reading the code; the code comments seem somewhat misleading (they talk about "extracting banking").

`[data] = crg_s2z(data, rz)`::
Apply new slope defined by `rz` to the OpenCRG data in `data`. Merge existing slope into the road data.
//TODO: Please check whether this is true. Got this from reading the code; the code comments seem somewhat misleading (they talk about "separating slope")..

`[data] = crg_ext_slope(data, p)`::
Extract the slope from OpenCRG data in `data`. `pp` is a smoothing parameter.

`[data] = crg_ext_banking(data, pp)`::
Extract the banking from OpenCRG data in `data`. `pp` is a smoothing parameter.

`[data] = crg_filter(data, iu, iv, fm, mask, wopt)`::
Filter OpenCRG data in `data`. `iu` and `iv` can be used to limit filtering to an area of the grid. `fm` specifies the filtering method. `mask` specifies the size of the filter mask. The optional `wopt` defines filter weights and number of repeated filterings.

`[data] = crg_limiter(data, mmlim, iu, iv)`::
Limit z-values in `data` to the minimum and maximum defined in `mmlim`. `iu` and `iv` can be used to limit the operation to an area of the grid.

`[data] = crg_wrap(data)`::
Wrap heading angles of road parameters and road data in `data` to a +/- pi range.

`[data] = crg_flip(data)`::
Flip the OpenCRG data in `data`, swapping start and end while leaving the modifiers and options unchanged.

`[data] = crg_map_uv2uv(data, crg_uv, iu, iv)`::
Map z-values of `crg_uv` in u/v-coordinates to the u/v-grid of `data`. `iu` and `iv` can be used to limit the operation to an area of the grid.

`[data] = crg_map_xy2xy(data, crg_xy, iu, iv)`::
Map z-values of `crg_xy` in x/y-coordinates to the inertial x/y-coordinate system of `data`. `iu` and `iv` can be used to limit the operation to an area of the grid.

`[data] = crg_rerender(crg, inc, v)`::
Re-render OpenCRG data in `crg` as `data` with new u/v-increment `inc` and v-spacing `v`.

==== Examples

===== Matlab examples

//TODO: Which examples would be of interest?

==== Related topics

// TODO: add related topics in the end.