=== Writing OpenCRG files

With the Matlab tools, OpenCRG files can be created from OpenCRG data in memory. These file use the KRBI format. Therefore, road data must be converted to type _single_ before writing it to file.

==== Prerequisites

* You have loaded or generated an OpenCRG data set.

==== Related C functions

The C-API does not provide functions for writing OpenCRG data.

==== Related Matlab functions

`[ier] = crg_write(data, file, type)`::
Write the OpenCRG data in `data` to the OpenCRG file `file`. By default the file uses the KRBI format. The optional argument `type` may be used to specify LRFI format instead. Therefore, road data must be converted to type _single_ first. `ier` indicates whether any errors occurred while writing the file.

`[data] = crg_single(data)`::
Convert road data in `data` to type _single_.

==== Examples

===== Matlab examples

The following example shows how to write the OpenCRG data in `data` to a KRBI file using the Matlab tools.

----
% write CRG file 
ier = crg_write(crg_single(data), 'demo.crg');
----

==== Related topics

* <<Road data>>