==== Library files of the Matlab tools

The library files of the Matlab tools are stored in `_open-crg_/matlab/lib/` and comprise the following:

// TODO: add descriptions once the code comments have been reviewed (maybe use include mechanism?)
// TODO: do we need this at all?

`copy_ax2fig.m`::  ???
`crg_append.m`::  ???
`crg_b2z.m`::  ???
`crg_check.m`::  ???
`crg_check_curvature.m`::  ???
`crg_check_curvature2.m`::  ???
`crg_check_data.m`::  ???
`crg_check_head.m`::  ???
`crg_check_mods.m`::  ???
`crg_check_mpro.m`::  ???
`crg_check_opts.m`::  ???
`crg_check_single.m`::  ???
`crg_check_uv_descript.m`::  ???
`crg_check_wgs84.m`::  ???
`crg_cut_iuiv.m`::  ???
`crg_eval_enh2xyz.m`::  ???
`crg_eval_llh2xyz.m`::  ???
`crg_eval_u2crv.m`::  ???
`crg_eval_u2phi.m`::  ???
`crg_eval_uv2iuiv.m`::  ???
`crg_eval_uv2xy.m`::  ???
`crg_eval_uv2z.m`::  ???
`crg_eval_xy2uv.m`::  ???
`crg_eval_xy2z.m`::  ???
`crg_eval_xyz2enh.m`::  ???
`crg_eval_xyz2llh.m`::  ???
`crg_ext_banking.m`::  ???
`crg_ext_slope.m`::  ???
`crg_figure.m`::  ???
`crg_filter.m`::  ???
`crg_flip.m`::  ???
`crg_gen_csb2crg0.m`::  ???
`crg_gen_ppxy2phi.m`::  ???
`crg_gen_pxy2ppxy.m`::  ???
`crg_isequal.m`::  ???
`crg_limiter.m`::  ???
`crg_map_uv2uv.m`::  ???
`crg_map_xy2xy.m`::  ???
`crg_mods.m`::  ???
`crg_peakfinder.m`::  ???
`crg_perform2surface.m`::  ???
`crg_plot_elgrid_cross_sect.m`::  ???
`crg_plot_elgrid_limits.m`::  ???
`crg_plot_elgrid_long_sect.m`::  ???
`crg_plot_elgrid_uvz_map.m`::  ???
`crg_plot_elgrid_xyz_map.m`::  ???
`crg_plot_refline_curvature.m`::  ???
`crg_plot_refline_elevation.m`::  ???
`crg_plot_refline_heading.m`::  ???
`crg_plot_refline_slope_bank.m`::  ???
`crg_plot_refline_xyz_map.m`::  ???
`crg_plot_refline_xy_map_and_curv.m`::  ???
`crg_plot_refline_xy_overview_map.m`::  ???
`crg_plot_refpnt_distances.m`::  ???
`crg_plot_road_uv2uvz_map.m`::  ???
`crg_plot_road_uv2xyz_map.m`::  ???
`crg_plot_road_uvz_map.m`::  ???
`crg_plot_road_xyz_map.m`::  ???
`crg_read.m`::  ???
`crg_rerender.m`::  ???
`crg_s2z.m`::  ???
`crg_separate_sb.m`::  ???
`crg_show.m`::  ???
`crg_show_elgrid_cuts_and_limits.m`::  ???
`crg_show_elgrid_surface.m`::  ???
`crg_show_info.m`::  ???
`crg_show_isequal.m`::  ???
`crg_show_peaks.m`::  ???
`crg_show_refline_elevation.m`::  ???
`crg_show_refline_map.m`::  ???
`crg_show_refpnts_and_refline.m`::  ???
`crg_show_road_surface.m`::  ???
`crg_show_road_uv2surface.m`::  ???
`crg_single.m`::  ???
`crg_surf.m`::  ???
`crg_wgs84_crg2html.m`::  ???
`crg_wgs84_dist.m`::  ???
`crg_wgs84_invdist.m`::  ???
`crg_wgs84_setend.m`::  ???
`crg_wgs84_wgs2url.m`::  ???
`crg_wgs84_wgsxy2wgs.m`::  ???
`crg_wgs84_xy2wgs.m`::  ???
`crg_wrap.m`::  ???
`crg_write.m`::  ???
`ipl_demo.m`::  ???
`ipl_read.m`::  ???
`ipl_write.m`::  ???
`map_check.m`::  ???
`map_check_elli.m`::  ???
`map_check_proj.m`::  ???
`map_check_tran.m`::  ???
`map_ecef2ecef.m`::  ???
`map_ecef2geod.m`::  ???
`map_geod2ecef.m`::  ???
`map_geod2pmap.m`::  ???
`map_geod2pmap_tm.m`::  ???
`map_global2plocal.m`::  ???
`map_intro.m`::  ???
`map_plocal2global.m`::  ???
`map_pmap2geod_tm.m`::  ???
`map_ptm_north2initiallat.m`::  ???
`map_ptm_phi2marc.m`::  ???
`map_wgs2html.m`::  ???
`sdf_add.m`::  ???
`sdf_cut.m`::  ???
`smooth_firfilt.m`::  ???
`str_num2strn.m`::  ???
