==== Library files of the Matlab tools

The library files of the Matlab tools are located in `_open-crg_/matlab/lib/` and comprise the following:

// TODO: add descriptions once the code comments have been reviewed (maybe use include mechanism?)

`/lib/copy_ax2fig.m`::  ???
`/lib/crg_append.m`::  ???
`/lib/crg_b2z.m`::  ???
`/lib/crg_check.m`::  ???
`/lib/crg_check_curvature.m`::  ???
`/lib/crg_check_curvature2.m`::  ???
`/lib/crg_check_data.m`::  ???
`/lib/crg_check_head.m`::  ???
`/lib/crg_check_mods.m`::  ???
`/lib/crg_check_mpro.m`::  ???
`/lib/crg_check_opts.m`::  ???
`/lib/crg_check_single.m`::  ???
`/lib/crg_check_uv_descript.m`::  ???
`/lib/crg_check_wgs84.m`::  ???
`/lib/crg_cut_iuiv.m`::  ???
`/lib/crg_eval_enh2xyz.m`::  ???
`/lib/crg_eval_llh2xyz.m`::  ???
`/lib/crg_eval_u2crv.m`::  ???
`/lib/crg_eval_u2phi.m`::  ???
`/lib/crg_eval_uv2iuiv.m`::  ???
`/lib/crg_eval_uv2xy.m`::  ???
`/lib/crg_eval_uv2z.m`::  ???
`/lib/crg_eval_xy2uv.m`::  ???
`/lib/crg_eval_xy2z.m`::  ???
`/lib/crg_eval_xyz2enh.m`::  ???
`/lib/crg_eval_xyz2llh.m`::  ???
`/lib/crg_ext_banking.m`::  ???
`/lib/crg_ext_slope.m`::  ???
`/lib/crg_figure.m`::  ???
`/lib/crg_filter.m`::  ???
`/lib/crg_flip.m`::  ???
`/lib/crg_gen_csb2crg0.m`::  ???
`/lib/crg_gen_ppxy2phi.m`::  ???
`/lib/crg_gen_pxy2ppxy.m`::  ???
`/lib/crg_isequal.m`::  ???
`/lib/crg_limiter.m`::  ???
`/lib/crg_map_uv2uv.m`::  ???
`/lib/crg_map_xy2xy.m`::  ???
`/lib/crg_mods.m`::  ???
`/lib/crg_peakfinder.m`::  ???
`/lib/crg_perform2surface.m`::  ???
`/lib/crg_plot_elgrid_cross_sect.m`::  ???
`/lib/crg_plot_elgrid_limits.m`::  ???
`/lib/crg_plot_elgrid_long_sect.m`::  ???
`/lib/crg_plot_elgrid_uvz_map.m`::  ???
`/lib/crg_plot_elgrid_xyz_map.m`::  ???
`/lib/crg_plot_refline_curvature.m`::  ???
`/lib/crg_plot_refline_elevation.m`::  ???
`/lib/crg_plot_refline_heading.m`::  ???
`/lib/crg_plot_refline_slope_bank.m`::  ???
`/lib/crg_plot_refline_xyz_map.m`::  ???
`/lib/crg_plot_refline_xy_map_and_curv.m`::  ???
`/lib/crg_plot_refline_xy_overview_map.m`::  ???
`/lib/crg_plot_refpnt_distances.m`::  ???
`/lib/crg_plot_road_uv2uvz_map.m`::  ???
`/lib/crg_plot_road_uv2xyz_map.m`::  ???
`/lib/crg_plot_road_uvz_map.m`::  ???
`/lib/crg_plot_road_xyz_map.m`::  ???
`/lib/crg_read.m`::  ???
`/lib/crg_rerender.m`::  ???
`/lib/crg_s2z.m`::  ???
`/lib/crg_separate_sb.m`::  ???
`/lib/crg_show.m`::  ???
`/lib/crg_show_elgrid_cuts_and_limits.m`::  ???
`/lib/crg_show_elgrid_surface.m`::  ???
`/lib/crg_show_info.m`::  ???
`/lib/crg_show_isequal.m`::  ???
`/lib/crg_show_peaks.m`::  ???
`/lib/crg_show_refline_elevation.m`::  ???
`/lib/crg_show_refline_map.m`::  ???
`/lib/crg_show_refpnts_and_refline.m`::  ???
`/lib/crg_show_road_surface.m`::  ???
`/lib/crg_show_road_uv2surface.m`::  ???
`/lib/crg_single.m`::  ???
`/lib/crg_surf.m`::  ???
`/lib/crg_wgs84_crg2html.m`::  ???
`/lib/crg_wgs84_dist.m`::  ???
`/lib/crg_wgs84_invdist.m`::  ???
`/lib/crg_wgs84_setend.m`::  ???
`/lib/crg_wgs84_wgs2url.m`::  ???
`/lib/crg_wgs84_wgsxy2wgs.m`::  ???
`/lib/crg_wgs84_xy2wgs.m`::  ???
`/lib/crg_wrap.m`::  ???
`/lib/crg_write.m`::  ???
`/lib/ipl_demo.m`::  ???
`/lib/ipl_read.m`::  ???
`/lib/ipl_write.m`::  ???
`/lib/map_check.m`::  ???
`/lib/map_check_elli.m`::  ???
`/lib/map_check_proj.m`::  ???
`/lib/map_check_tran.m`::  ???
`/lib/map_ecef2ecef.m`::  ???
`/lib/map_ecef2geod.m`::  ???
`/lib/map_geod2ecef.m`::  ???
`/lib/map_geod2pmap.m`::  ???
`/lib/map_geod2pmap_tm.m`::  ???
`/lib/map_global2plocal.m`::  ???
`/lib/map_intro.m`::  ???
`/lib/map_plocal2global.m`::  ???
`/lib/map_pmap2geod_tm.m`::  ???
`/lib/map_ptm_north2initiallat.m`::  ???
`/lib/map_ptm_phi2marc.m`::  ???
`/lib/map_wgs2html.m`::  ???
`/lib/sdf_add.m`::  ???
`/lib/sdf_cut.m`::  ???
`/lib/smooth_firfilt.m`::  ???
`/lib/str_num2strn.m`::  ???
